config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  require 'sidekiq/web'

  match '/auth/:provider/callback' => 'authentications#create', via: [:get, :post]
  match '/auth/failure' => 'authentications#failure', via: [:get, :post]

  match '/auth/olo/authorize' => 'auth#authorize', via: [:get, :post]
  match '/auth/olo/authorize_mobile_app' => 'auth#authorize_mobile_app', via: [:get, :post]
  match '/auth/olo/access_token' => 'auth#access_token', via: [:get, :post]
  match '/auth/olo/user' => 'auth#user', via: [:get, :post]
  match '/auth/olo/logout' => 'auth#session_destroy', via: [:get, :post]
  match '/oauth/token' => 'auth#access_token', via: [:get, :post]

  match 'authentications/:user_id/link' => 'authentications#link', :as => :link_accounts, via: [:get, :post]
  match 'authentications/:user_id/add' => 'authentications#add', :as => :add_account, via: [:get, :post]

  match "login_oauth" => "authentications#login_oauth", :as => :login_oauth, via: [:get, :post]

  get "users/:id/email_confirm" => "menus#confirm_email", :as => :confirm_email
  get "terms_of_use" => "menus#terms_of_use", :as => :tou
  get "privacy_policy" => "menus#privacy_policy", :as => :privacy_policy
  get "faq" => "menus#faq", :as => :faq
  get "faqs/:faq_data" => "menus#generated_faq", :as => :generated_faq
  get "about_us" => "menus#about_us", :as => :about_us
  get "contact_us_faq" => "menus#contact_us_faq", :as => :contact_us_faq
  get "game_faq" => "menus#game_faq", :as => :game_faq
  get "url/:chain_id/:url_id" => "menus#url", :as => :chain_url
  get "download_reward_transactions" => "menus#download_reward_transactions", :as => :download_reward_transactions
  get 'receipt/:url_id' => "menus#show_receipt", :as => :show_receipt
  post "status_url_skrill_payment" => "menus#status_url_skrill_payment", :as => :status_url_skrill_payment

  post "olo_webhook/:chain_name", :to => "api/v1/olo_webhooks#create_olo"
  get "receive", :to => "api/v1/olo_webhooks#index"

  devise_for :owners, :controllers => { :sessions => "owner/sessions" }
  devise_scope :owner do
   get "owner/log_in", :to => "owner/sessions#new"
   post "owner/log_in", :to => "owner/sessions#create"
   get "owner/log_out", :to => "owner/sessions#destroy"
 end

  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end

  devise_scope :owner do
    get "owner/log_in", :to => "owner/sessions#new"
    post "owner/log_in", :to => "owner/sessions#create"
    get "owner/log_out", :to => "owner/sessions#destroy"
    put "owner/:id" => 'owner/registrations#update', :as => 'owner_registration_update'
  end

  namespace :owner do
    resources :greetings, :path => "/summaries" do
      collection do
        get :search_summaries
        get :export_summaries
      end
    end

    resources :guest_relations, :path => "/request" do
      collection do
        get :search_status_relation
      end

      member do
        get "check_status_relation"
        post "update_status_relation"
        get "approve_or_reject"
      end
    end

    resources :owner_jobs, :path => "/jobs" do
      collection do
        get :search_users
        get :miss_you
        get :new_miss_you
        get :individual
        post :create_individual
        post :create_miss_job
        get :search_job_type
      end
      member do
        get 'completed_job'
      end
    end
    resources :members do
      collection do
        post :send_message
        post :search
      end
    end
    resources :owner_users do
      collection do
        get :export_pdf, :format => :pdf
      end
    end
    resources :surveys do
      collection do
        match '/all_survey' => "surveys#all_survey", via: [:get, :post]
        get :export_survey_dashboard
        get :search_location_survey
        get :search_all_survey
        get :search
        get :search_chart
        post :process_request
        get :request_csv
        post :submit_request_csv
      end

      member do
        get "request_guest_relation"
        post "request_guest"

      end
    end
    resources :rewards
    resources :activities do
      collection do
        get :search_activities
        post :generate_restaurant
        post :generate_restaurant_rewards
        post :print_row_tables
        post :print_row_tables_rewards
        get :rewards
        post :export_rewards_redeemed
        post :export_activities
      end
      member do
        get :show_detail_receipt
        get :show_detail_reward
        get :show_popup_reward_activities
        get :show_receipt_barcode
        get :show_online_order
        get :show_olo_order
      end
    end
  end

  resource :charts do
    collection do
      get :active_members
      get :members
      get :average_frequency
      get :average_check_frequency
      get :frequency
      get :top5_surveys
      get :average_surveys
      get :avg_surveys
      get :survey_question1
      get :survey_question2
      get :survey_question3
      get :survey_question4
    end
  end

  scope '(:locale)' do
    devise_for :admin, skip: :registrations, controllers: {sessions: 'admin/sessions'} do
      get "sign_in" , to: "admin/sessions#new", as: :admin_sign_in
      get "log_in" , to: "admin/sessions#new", as: :new_admin_log_in
      post "log_in" , to: "admin/sessions#create", as: :admin_log_in
      get "log_out" , to: "admin/sessions#destroy", as: :admin_log_out
    end
  end
  devise_for :users, :controllers => {
    :sessions => "user/sessions", :registrations => "user/registrations", :omniauth_callbacks=>'user/omniauth_callbacks',
    :passwords => "user/passwords"
  }
  devise_scope :user do
    get "user/log_in", :to => "user/sessions#new"
    post "user/log_in", :to => "user/sessions#create"
    get "user/log_out", :to => "user/sessions#destroy"
  end

  namespace :admin do
    mount Sidekiq::Web => '/sidekiq_redis'

    resources :partner_rewards do
      collection do
        post :search
        get :search
        get :load_categories
        get :load_restaurants
      end
    end
    resources :partner_categories do
      resources :partner_sub_categories
    end
    resources :partner_sub_categories do
      collection do
        post :load_restaurants
        get :load_menu_items
      end
      member do
        post :update_participation
        post :add_item
        post :remove_item
        get :search_menu_items
      end
    end
    resources :partner_menu_items do
      collection do
        post :load_restaurants
      end
    end
    resources :partner_code_settings do
      collection do
        post 'search', :to => "partner_code_settings#search"
      end
    end
    resources :partner_webhook_settings do
      collection do
        post 'search', :to => "partner_webhook_settings#search"
      end
    end

    resources :vantiv_gift_card_email_sent_logs, except: [:edit, :update, :destroy, :new, :create] do
      collection do
        match "search", via: [:get, :post]
      end

      member do
        post :resend_mail
      end
    end
    resources :push_service_notifications, except: [:edit, :update, :destroy], path: "push_services" do
      member do
        get "progress"
        get "cancel"
        get "resume"
        get "pause"
        get 'load_user_list'
      end
      collection do
        get 'sync'
        get 'get_time'
        get 'dashboard'
        get 'ipost'
      end
    end
    resources :push_service_points, except: [:edit, :update, :destroy] do
      member do
        get "progress"
        get "cancel"
        get "resume"
        get "pause"
      end
      collection do
        get 'sync'
      end
    end

    resources :papa_murphys, as: :papa_murphy_reports
    resources :webhooks do
      member do
        get "process_receipt_olo"
      end
    end

    resources :olo_orders do
      collection do
        post 'search'
        match 'olo_receipt_detail', :as => :olo_receipt_detail, via: :get
      end
      member do
        get "order_details"
        match "/order_details/:detail_id" ,:to => "olo_orders#olo_order_show", :via => :get , :as => :olo_order_show
        match "/order_detail_edit/:detail_id" ,:to => "olo_orders#olo_order_edit", :via => :get , :as => :olo_order_edit
        get "process_olo_detail"
        put "post_detail_olo"
        post "batch_process"
      end
    end

    resources :comments, :path => 'email_list' do
      member do
        get "update_email_process" => "comments#update_email_process"
        get "process_receipt" => "comments#process_receipt"
        get "nokogiri_parse_email" => "comments#nokogiri_parse_email"
      end
    end

    resources :miss_you_tasks do
      collection do
        get 'search'
        get 'testing_activation'
      end
      member do
        get 'sending_report'
        post 'post_sending_report_miss_you'
        get 'completed_job'
        put 'update_from_admin'
        get 'update_step',:format => :js
        post 'update_step_ajax',:format => :js
      end
    end

    resources :no_scan_tasks do
      collection do
        get 'search'
        get 'testing_activation'
      end
      member do
        get 'completed_job'
        put 'update_from_admin'
        get 'update_step',:format => :js
        post 'update_step_ajax',:format => :js
      end
    end

    resources :owner_jobs do
      collection do
        get 'search'
        get 'testing_activation'
      end
      member do
        get 'completed_job'
        put 'update_from_admin'
        get 'update_step',:format => :js
        post 'update_step_ajax',:format => :js
      end
    end
    resources :jobs
    resources :admin_jobs,:except => [:show, :edit, :destroy, :update]

    resources :report_subscriptions do
      collection do
        get "search_chain"
        get "search_report_description"
        get "report_settings"
        post "post_test_report"
      end

      member do
        get "subscription_filename"

app/controllers/admin/user_notifications_controller.rb
class Admin::UserNotificationsController < Admin::BaseController

  before_action :find_chain

  def  index
    @user_notifications = @chain.user_activity_notifications
  end

  def new
    @user_notification = @chain.user_activity_notifications.new(:unique_identifier => Time.zone.now.to_i)
    @user_notification.user_activity_notification_fields.build
  end

  def create
    begin
      @user_notification = @chain.user_activity_notifications.new(params[:user_activity_notification])
      if @user_notification.save
        redirect_to admin_chain_user_notifications_path(@chain), :notice => "User Activity Notification Based has been created."
      else
        render :new
      end
    rescue ActiveRecord::NestedAttributes::TooManyRecords
      params[:user_activity_notification].delete(:user_activity_notification_fields_attributes)
      @user_notification = @chain.user_activity_notifications.new(params[:user_activity_notification]) if @user_notification.blank?
      @user_notification.errors.add(:user_activity_notification_fields, "To Many records, Max 5 allowed.")
      render :new
    end
  end

  def edit
    @user_notification = @chain.user_activity_notifications.find(params[:id])
  end

  def update
    @user_notification = @chain.user_activity_notifications.find(params[:id])

    begin
      if @user_notification.update_attributes(params[:user_activity_notification])
        redirect_to admin_chain_user_notifications_path(@chain), :notice => "User Activity Notification Based has been updated."
      else
        render :edit
      end
    rescue ActiveRecord::NestedAttributes::TooManyRecords
      @user_notification.errors.add(:user_activity_notification_fields, "To Many records, Max 5 allowed.")
      render :edit
    end
  end

  def destroy
    @user_notification = @chain.user_activity_notifications.find(params[:id])
    @user_notification.destroy
    redirect_to admin_chain_user_notifications_path(@chain), :notice => "User Activity Notification Based has been deleted."
  end

  protected

  def find_chain
    @chain = Chain.find(params[:chain_id])
  end

end

app/views/admin/user_notifications/_form.html.erb
<% if @user_notification.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user_notification.errors.count, "error") %> prohibited this chain from being saved:</h2>

    <ul>
      <% @user_notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.input :unique_identifier, :readonly => true %>
</div>
<div class="field">
  <%= f.input :description %>
</div>
<div class="field">
  <%= f.input :notification, :input_html => {:style => "height:150px;width:400px;"} %>
</div>
<div class="field">
  <%= f.input :delay_time %> <i> Delay in seconds, 0 = no delay </i>
</div>
<br />
<div class="field">
  <label class="text required control-label" for="dynamic_fields">
    Dynamic Fields <i> (max : 5 fields allowed)</i>:
  </label>

  <div class="clearfix"></div>
  <div id="user_activity_fields">
    <%= f.simple_fields_for :user_activity_notification_fields do |user_activity_notification| %>
      <%= render "user_activity_notification_field_fields", :f => user_activity_notification %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add dynamic fields text', f, :user_activity_notification_fields, :class => "btn btn-primary"%>
    </div>
  </div>
</div>
<br/>
<br/>
<div class="actions">
  <%= f.submit :class => "btn btn-primary" %>
</div>

app/views/admin/user_notifications/_user_activity_notification_field_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.input :name %>
  </div>
  <div class="field">
    <%= f.input :description %>
  </div>
  <div class="field">
    <%= f.input :identifier %>
  </div>
  <div class="field span4" style="margin-left: 420px;">
    <%= link_to_remove_association "remove", f, :class => "btn btn-danger" %>
  </div>
  <div class="clearfix"></div>
  <br />
</div>

app/views/admin/user_notifications/edit.html.erb
<div class="page-header">
  <h3>Edit User Activity Based Notification</h3>
</div>
<%= simple_form_for([:admin, @user_notification], :url => admin_chain_user_notification_path(@chain, @user_notification), :html => {:class => "form-horizontal", :method => :put}) do |f| %>
    <%= render 'form', :f => f %>
<% end %>
<%= link_to 'Back', admin_chain_user_notifications_path(@chain) %>

app/views/admin/user_notifications/index.html.erb
<div class="page-header">
  <h2>Listing User Activity Based Notification <%= @chain.name %></h2>
</div>
<table class="table table-bordered table-condensed">
  <thead>
  <tr>
    <th width="10%">Unique Identifier</th>
    <th width="5%">Delay</th>
    <th>Description</th>
    <th>Notification</th>
    <th>Fields</th>
    <th width="15%">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @user_notifications.each do |user_notification| %>
      <tr>
        <td><%= user_notification.unique_identifier %></td>
        <td><%= user_notification.delay_time %></td>
        <td><%= user_notification.description %></td>
        <td><%= user_notification.notification %></td>
        <td>
          <% user_notification.user_activity_notification_fields.each do |a| %>
            Name  : <%= a.name %> <br />
            Description  : <%= a.description %> <br />
            Identifier  : <%= a.identifier %> <br />
              <hr />
          <% end %>
        </td>
        <td>
          <%= link_to 'Destroy', admin_chain_user_notification_path(@chain, user_notification), :class => "btn btn-danger", :method => :delete, :confirm => 'are you sure?' %>
          <%= link_to 'Edit', edit_admin_chain_user_notification_path(@chain, user_notification), :class => "btn btn-warning" %>
        </td>
      </tr>
  <% end %>
  <% if @user_notifications.blank? %>
      <tr><td colspan="6">There are no data</td></tr>
  <% end %>
  </tbody>
</table>
<br/>
<%= link_to 'New Notification Share', new_admin_chain_user_notification_path(@chain), :class => "btn btn-primary" %>
<%= link_to 'Back', admin_chains_path, :class => "btn btn-primary" %>

app/views/admin/user_notifications/new.html.erb
<div class="page-header">
  <h3>New User Activity Based Notification</h3>
</div>
<%= simple_form_for([:admin, @user_notification], :url => admin_chain_user_notifications_path(@chain), :html => {:class => "form-horizontal"}) do |f| %>
    <%= render 'form', :f => f %>
<% end %>
<%= link_to 'Back', admin_chain_user_notifications_path(@chain) %>