config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  require 'sidekiq/web'

  match '/auth/:provider/callback' => 'authentications#create', via: [:get, :post]
  match '/auth/failure' => 'authentications#failure', via: [:get, :post]

  match '/auth/olo/authorize' => 'auth#authorize', via: [:get, :post]
  match '/auth/olo/authorize_mobile_app' => 'auth#authorize_mobile_app', via: [:get, :post]
  match '/auth/olo/access_token' => 'auth#access_token', via: [:get, :post]
  match '/auth/olo/user' => 'auth#user', via: [:get, :post]
  match '/auth/olo/logout' => 'auth#session_destroy', via: [:get, :post]
  match '/oauth/token' => 'auth#access_token', via: [:get, :post]

  match 'authentications/:user_id/link' => 'authentications#link', :as => :link_accounts, via: [:get, :post]
  match 'authentications/:user_id/add' => 'authentications#add', :as => :add_account, via: [:get, :post]

  match "login_oauth" => "authentications#login_oauth", :as => :login_oauth, via: [:get, :post]

  get "users/:id/email_confirm" => "menus#confirm_email", :as => :confirm_email
  get "terms_of_use" => "menus#terms_of_use", :as => :tou
  get "privacy_policy" => "menus#privacy_policy", :as => :privacy_policy
  get "faq" => "menus#faq", :as => :faq
  get "faqs/:faq_data" => "menus#generated_faq", :as => :generated_faq
  get "about_us" => "menus#about_us", :as => :about_us
  get "contact_us_faq" => "menus#contact_us_faq", :as => :contact_us_faq
  get "game_faq" => "menus#game_faq", :as => :game_faq
  get "url/:chain_id/:url_id" => "menus#url", :as => :chain_url
  get "download_reward_transactions" => "menus#download_reward_transactions", :as => :download_reward_transactions
  get 'receipt/:url_id' => "menus#show_receipt", :as => :show_receipt
  post "status_url_skrill_payment" => "menus#status_url_skrill_payment", :as => :status_url_skrill_payment

  post "olo_webhook/:chain_name", :to => "api/v1/olo_webhooks#create_olo"
  get "receive", :to => "api/v1/olo_webhooks#index"

  devise_for :owners, :controllers => { :sessions => "owner/sessions" }
  devise_scope :owner do
   get "owner/log_in", :to => "owner/sessions#new"
   post "owner/log_in", :to => "owner/sessions#create"
   get "owner/log_out", :to => "owner/sessions#destroy"
 end

  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end

  devise_scope :owner do
    get "owner/log_in", :to => "owner/sessions#new"
    post "owner/log_in", :to => "owner/sessions#create"
    get "owner/log_out", :to => "owner/sessions#destroy"
    put "owner/:id" => 'owner/registrations#update', :as => 'owner_registration_update'
  end

  namespace :owner do
    resources :greetings, :path => "/summaries" do
      collection do
        get :search_summaries
        get :export_summaries
      end
    end

    resources :guest_relations, :path => "/request" do
      collection do
        get :search_status_relation
      end

      member do
        get "check_status_relation"
        post "update_status_relation"
        get "approve_or_reject"
      end
    end

    resources :owner_jobs, :path => "/jobs" do
      collection do
        get :search_users
        get :miss_you
        get :new_miss_you
        get :individual
        post :create_individual
        post :create_miss_job
        get :search_job_type
      end
      member do
        get 'completed_job'
      end
    end
    resources :members do
      collection do
        post :send_message
        post :search
      end
    end
    resources :owner_users do
      collection do
        get :export_pdf, :format => :pdf
      end
    end
    resources :surveys do
      collection do
        match '/all_survey' => "surveys#all_survey", via: [:get, :post]
        get :export_survey_dashboard
        get :search_location_survey
        get :search_all_survey
        get :search
        get :search_chart
        post :process_request
        get :request_csv
        post :submit_request_csv
      end

      member do
        get "request_guest_relation"
        post "request_guest"

      end
    end
    resources :rewards
    resources :activities do
      collection do
        get :search_activities
        post :generate_restaurant
        post :generate_restaurant_rewards
        post :print_row_tables
        post :print_row_tables_rewards
        get :rewards
        post :export_rewards_redeemed
        post :export_activities
      end
      member do
        get :show_detail_receipt
        get :show_detail_reward
        get :show_popup_reward_activities
        get :show_receipt_barcode
        get :show_online_order
        get :show_olo_order
      end
    end
  end

  resource :charts do
    collection do
      get :active_members
      get :members
      get :average_frequency
      get :average_check_frequency
      get :frequency
      get :top5_surveys
      get :average_surveys
      get :avg_surveys
      get :survey_question1
      get :survey_question2
      get :survey_question3
      get :survey_question4
    end
  end

  scope '(:locale)' do
    devise_for :admin, skip: :registrations, controllers: {sessions: 'admin/sessions'} do
      get "sign_in" , to: "admin/sessions#new", as: :admin_sign_in
      get "log_in" , to: "admin/sessions#new", as: :new_admin_log_in
      post "log_in" , to: "admin/sessions#create", as: :admin_log_in
      get "log_out" , to: "admin/sessions#destroy", as: :admin_log_out
    end
  end
  devise_for :users, :controllers => {
    :sessions => "user/sessions", :registrations => "user/registrations", :omniauth_callbacks=>'user/omniauth_callbacks',
    :passwords => "user/passwords"
  }
  devise_scope :user do
    get "user/log_in", :to => "user/sessions#new"
    post "user/log_in", :to => "user/sessions#create"
    get "user/log_out", :to => "user/sessions#destroy"
  end

  namespace :admin do
    mount Sidekiq::Web => '/sidekiq_redis'

    resources :partner_rewards do
      collection do
        post :search
        get :search
        get :load_categories
        get :load_restaurants
      end
    end
    resources :partner_categories do
      resources :partner_sub_categories
    end
    resources :partner_sub_categories do
      collection do
        post :load_restaurants
        get :load_menu_items
      end
      member do
        post :update_participation
        post :add_item
        post :remove_item
        get :search_menu_items
      end
    end
    resources :partner_menu_items do
      collection do
        post :load_restaurants
      end
    end
    resources :partner_code_settings do
      collection do
        post 'search', :to => "partner_code_settings#search"
      end
    end
    resources :partner_webhook_settings do
      collection do
        post 'search', :to => "partner_webhook_settings#search"
      end
    end

    resources :vantiv_gift_card_email_sent_logs, except: [:edit, :update, :destroy, :new, :create] do
      collection do
        match "search", via: [:get, :post]
      end

      member do
        post :resend_mail
      end
    end
    resources :push_service_notifications, except: [:edit, :update, :destroy], path: "push_services" do
      member do
        get "progress"
        get "cancel"
        get "resume"
        get "pause"
        get 'load_user_list'
      end
      collection do
        get 'sync'
        get 'get_time'
        get 'dashboard'
        get 'ipost'
      end
    end
    resources :push_service_points, except: [:edit, :update, :destroy] do
      member do
        get "progress"
        get "cancel"
        get "resume"
        get "pause"
      end
      collection do
        get 'sync'
      end
    end

    resources :papa_murphys, as: :papa_murphy_reports
    resources :webhooks do
      member do
        get "process_receipt_olo"
      end
    end

    resources :olo_orders do
      collection do
        post 'search'
        match 'olo_receipt_detail', :as => :olo_receipt_detail, via: :get
      end
      member do
        get "order_details"
        match "/order_details/:detail_id" ,:to => "olo_orders#olo_order_show", :via => :get , :as => :olo_order_show
        match "/order_detail_edit/:detail_id" ,:to => "olo_orders#olo_order_edit", :via => :get , :as => :olo_order_edit
        get "process_olo_detail"
        put "post_detail_olo"
        post "batch_process"
      end
    end

    resources :comments, :path => 'email_list' do
      member do
        get "update_email_process" => "comments#update_email_process"
        get "process_receipt" => "comments#process_receipt"
        get "nokogiri_parse_email" => "comments#nokogiri_parse_email"
      end
    end

    resources :miss_you_tasks do
      collection do
        get 'search'
        get 'testing_activation'
      end
      member do
        get 'sending_report'
        post 'post_sending_report_miss_you'
        get 'completed_job'
        put 'update_from_admin'
        get 'update_step',:format => :js
        post 'update_step_ajax',:format => :js
      end
    end

    resources :no_scan_tasks do
      collection do
        get 'search'
        get 'testing_activation'
      end
      member do
        get 'completed_job'
        put 'update_from_admin'
        get 'update_step',:format => :js
        post 'update_step_ajax',:format => :js
      end
    end

    resources :owner_jobs do
      collection do
        get 'search'
        get 'testing_activation'
      end
      member do
        get 'completed_job'
        put 'update_from_admin'
        get 'update_step',:format => :js
        post 'update_step_ajax',:format => :js
      end
    end
    resources :jobs
    resources :admin_jobs,:except => [:show, :edit, :destroy, :update]

    resources :report_subscriptions do
      collection do
        get "search_chain"
        get "search_report_description"
        get "report_settings"
        post "post_test_report"
      end

      member do
        get "subscription_filename"

app/models/locale.rb
class Locale < ActiveRecord::Base
	
  has_many :users
  has_many :chain_locales
  has_many :chains, :through => :chain_locales
  has_one :term
  
  default_scope { where("deleted_at" => nil) }

  def self.deleted
    self.unscoped.where('deleted_at IS NOT NULL')
  end
  
  
end

app/controllers/api/v2/survey_controller.rb
class Api::V2::SurveyController < Api::V1::SurveyController

  def index
    super
  end

  def show
    super
  end

  def getSurvey
    super
  end

  def answer
    super
  end

  def pull
    super
  end

  def skip
    super
  end

end

app/controllers/owner/base_controller.rb
class Owner::BaseController < ApplicationController
  layout 'owner_d2'
  before_action :authenticate_owner! , :find_email_to
#  before_action :find_chain
#
#  def find_chain
#    @chain = current_owner.chains.first
#    return @chain
#  end

  def find_email_to
    ch = current_owner.chain
    @email_to = REDIS.get "owner_question_email_chain_#{ch.id}"  rescue "support@relevantmobile.com"
    @email_to ||= "pleasesetonadmin@relevant.com"
    chain_ids = current_owner.chains.map(&:id)
    @request_count = GuestRelation.where("chain_id in(?) and status = 1", chain_ids).count if current_owner.is_chain_owner?
    @is_avg = REDIS.get "avg_survey_setting_#{ch.id}"
    @is_avg = @is_avg.blank?
  end

end

app/controllers/owner/members_controller.rb
class Owner::MembersController < Owner::BaseController
  #around_filter :select_shard
  before_action :find_chain_for_chart

  def index
    @tag_list = []
    @filter_tag = params['tag']

    if params['tag'] and params['tag'].include?('All')
      return redirect_to owner_members_path
    end

    if !params["tag"].blank?
      sql_conditions = " restaurants.chain_id = #{current_owner.chain.id} "
      @restaurants = Restaurant.tagged_with(params["tag"],sql_conditions)
    end

    a = Time.now
    puts "New member today process =========="
    # @new_member_today = Rails.cache.fetch("member_index_new_member_#{current_owner.id}_", :expires_in => 3.hours) do
    #  Chain.today_users(@chains,current_owner, @all_restaurants)
    # end
    @new_member_today = Chain.today_users(@chains,current_owner, @all_restaurants)
    puts "New member today process ========== in #{Time.now - a}"


    #@all_member = Rails.cache.fetch("member_index_all_member_#{@all_restaurants.map(&:id).join('_')}",
    #@all_member = Rails.cache.fetch("member_index_all_member_#{current_owner.id}",
    #                                                  :expires_in => 15.minutes) do
    # move to redis
     @all_member =  Chain.count_members(current_owner, @chains, @all_restaurants)
    #end
    a = Time.now
    puts "active member process =========="
    # @active_members_count =Rails.cache.fetch("member_index_active_member_new_1#{current_owner.id}",
    #                                          :expires_in => 3.hours) do
    #   Chain.new_count_active(@chains.first,@all_restaurants, @all_member)
    #
    # end
    @active_members_count = Chain.new_count_active(@chains.first,@all_restaurants, @all_member)
    puts "active member process ==========  in #{Time.now - a}"
    #@new_member_today = Chain.today_users(@chains,current_owner, @restaurants)
    #@all_member = Chain.count_members(current_owner, @chains, @restaurants)
    #@active_members_count = Chain.count_active_members(@restaurants, @all_member)
    #@active_members_count = Chain.new_count_active(@chains.first,@restaurants, @all_member)
    if @filter_location.blank?
      @selected_restaurants = [@restaurants[0]] if @restaurants.size <= 10
      @selected_restaurants = @restaurants[0..2] if @restaurants.size > 10
    else
      @selected_restaurants = @restaurants
    end

    @tag_list = Tagging.
        where("taggable_type = 'Restaurant' and taggable_id in (select id from restaurants where chain_id = #{@chain.id} and restaurants.status is TRUE) ").
        joins(:tag).select("distinct(tags.name)").map(&:name)
  end

  def send_message
    send_to = REDIS.get "owner_question_email_chain_#{@chain.id}" rescue nil
    ## if send to is not set on admin sent to support@relevantmobile.com
    send_to = "support@relevantmobile.com" if send_to.blank?

    OwnerMailer.send_to_support(
        @chain, send_to, params[:subject], params[:detail], params[:from],
        current_owner.email
    ).deliver!

    redirect_to :back, :notice => "Thanks for your feedback."
  end

  def search
    respond_to do |format|
      format.js {}
    end
  end

  private


  def select_shard(&block)
    ## turn on if environtment != trelevant
    puts "SELECT SHARD Session--------------------------------- "
    Octopus.using(:shard_one, &block)  #if ENV["S3_BUCKET"]  != "trelevant"
  end

  def find_chain_for_chart
    #current_owner = Owner.find_by_email("gp@relevantmobile.com")
    # @restaurants = Rails.cache.fetch("find_restaurant_for_chart_#{current_owner.id}",
    #                                                       :expires_in => 6.hours) do
    #   current_owner.restaurant_list.to_a
    # end

    @restaurants = current_owner.restaurant_list
    @all_restaurants = @restaurants
    @chain = current_owner.chain
    @chains = current_owner.chain_list
    ## this is commented out since the feature is hold
    #@filter_location = REDIS.get "owner_dashboard_setting_#{@chain.id}_location"
  end

end

app/controllers/owner/omniauth_callbacks_controller.rb
class Owner::OmniauthCallbacksController  < Devise::OmniauthCallbacksController
  layout 'owner'
  def facebook
    # You need to implement the method below in your model
    @owner = Owner.find_for_facebook_oauth(request.env["omniauth.auth"], current_owner)

    if @owner.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @owner, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_owner_registration_url
    end
  end
end

app/controllers/owner/owner_users_controller.rb
class Owner::OwnerUsersController < ApplicationController
  layout 'owner'
  skip_before_action :authenticate_user!, :only => [:export_pdf]

  def index
    @owner_users = current_owner.owner_users.paginate(page: params[:page], per_page: 10)
  end


  def show    
    @owner = Owner.find(params[:id])
  end

  def new    
    @owner = Owner.new
  end

  def create    
    @owner = Owner.new(params[:owner])
    respond_to do |format|
      if @owner.save
        @owner.update_attribute(:parent_id, current_owner.id)
        @owner.update_participation_restaurant(params[:restaurants], params[:ids])
        @owner.set_chain(@owner.chain_id)
        format.html { redirect_to owner_owner_users_url(@owner), notice: 'Owner was successfully updated.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def export_pdf    
    if Digest::SHA1.hexdigest(params[:ref_id]+"secret") == params["secret_keys"]      
      respond_to do |format|
        format.html
        format.pdf do
          render :pdf => "file_name"
        end
      end
    else
      render :text => "You dont have any permission for this"
    end
  end

  def edit    
    @owner = Owner.find(params[:id])
  end

  def update    
    @owner = Owner.find(params[:id])
    respond_to do |format|
      if @owner.update_attributes(params[:owner]) && @owner.update_attribute(:parent_id, current_owner.id)
        @owner.update_participation_restaurant(params[:restaurants], params[:ids])
        format.html { redirect_to owner_owner_users_url(@owner), notice: 'Owner was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy    
    @owner = Owner.find(params[:id])

    if(@owner)
      @owner.restaurants_owners.destroy_all
      @owner.destroy
    end

    redirect_to owner_owner_users_url
  end
end

app/views/owner/surveys/all_survey.html.erb
<div class="row-fluid section">
  <div class="span12 title2">
    <% if params['id'].blank? and params['survey_id'].blank? %>
        <h2>All survey data
          <% if current_owner.visible_create_request? %>
          <a href="#myModal" style="background:grey;color:white;" role="button" class="btn pull-right"
             data-toggle="modal" data-backdrop="static" data-keyboard="false"
             alt="click here to see the tutorial">Help</a>
              <% end %>
        </h2>
    <% else %>
        <h2><%= @survey.title %>
          <% if current_owner.visible_create_request? %>
          <a href="#myModal" data-backdrop="static" data-keyboard="false"
             style="background:grey;color:white;" role="button" class="btn pull-right" data-toggle="modal" alt="click here to see the tutorial">Help</a>
           <% end %>
        </h2>
    <% end %>
  </div>
  <br/><br/>

  <div class="span12" style="margin-left: 0px;">
    <div class="btn-group" style="float:left;">
      <button data-toggle="dropdown" class="btn dropdown-toggle">
        <% if params[:survey_id].blank? %>
            Select Survey
        <% else %>
            <%= @survey.title %>
        <% end %>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <!--<li><%#= link_to "All Survey", all_survey_owner_surveys_path %></li>-->
        <!--<li class="divider"></li>-->
        <% @surveys.each do |survey| %>
            <li>
              <%= link_to survey.title, all_survey_owner_surveys_path(:survey_id => survey.id) %>
            </li>
        <% end %>
      </ul>
    </div>
    &nbsp;&nbsp;&nbsp;
      <div class="btn-group">
            <button class="btn glow">Download Survey</button>
            <button data-toggle="dropdown" class="btn glow dropdown-toggle">
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <a href="#surModal" role="button" class="survey_csv" data-toggle="modal" id="survey_load" data-backdrop="static" data-keyboard="false" style="display:none;"></a>
              <% rgs= RotatingGroup.where(:chain_id => @chain_ids.first) %>
              <% rgs_ids = rgs.map(&:survey_id).uniq %>
              <li class="nav-header" style="margin-left:10px;"><b>General Survey</b></li>
              <% @surveys.each do |survey| %>
                <li>
                  <%= link_to "#{survey.title}", "#",
                              :onclick => "confirm_survey(#{survey.id},null);return true;" %>
                  <%= link_to "#{survey.title}",
                              request_csv_owner_surveys_path(:survey_id => survey.id),
                              :remote => true, :class => "survey_export",
                              :id => "survey_export_#{survey.id}", :style => "display:none;" %>
                </li>
              <% end %>

              <% unless rgs.blank? %>
              <li class="divider"></li>
              <li class="nav-header" style="margin-left:10px;"><b>Rotating Group</b></li>
                <% rgs.each do |m| %>
                    <li>
                      <%= link_to "#{m.name}", "#", :onclick => "confirm_survey(#{m.id},'rotating');return true;" %>
                      <%= link_to "#{m.name}",
                                  request_csv_owner_surveys_path(:rotating_id => m.id,:rotating => 'true'),
                                  :remote => true,
                                  :class => "survey_export_rotate",
                                  :id => "survey_export_#{m.id}_rotating",:target => "_blank",
                                  :style => 'display:none;' %>
                    </li>
                <% end %>
              <% else %>

              <% end %>
            </ul>
        </div>
    <%# x = "<i class='icon-file'></i>" %>

    <%#= link_to "#{x}Export to csv".html_safe, request.parameters.merge({:format => :csv}),:class => "btn", :style => "width:%;" %>
  </div>
  <br /><br />
  <%= render 'search_request_bar' %>

  <div class="span6 input-append" style="margin-left: 0px; margin-bottom: 0px;">
    <%= form_tag({:controller => "surveys", :action => "search_all_survey"}, :id => 'x-search-survey', :remote => true, :method => :get, :style => "float: left; padding-left: 0px; width: 500px;", :class => "input-append") do |f| %>
        <%= text_field_tag "search[q]", '', :placeholder => "Search by member or location", :class => "span8 leftcraft" %>
        <%= link_to "Search","#", :class => "btn",
                    :onclick => "
         if($('#search_q').val() != '' || $('#status').val() != '0' || $('#search_from').val() != '' || $('#search_to').val() != ''){
                    $('#name_member').val($('#search_q').val());
                    $('#tableContainer').ajaxloader();
                    $('#form_up').click();
                    return false;}else{
                      window.location = '/owner/surveys/all_survey'
                    }
                    " %>
    <% end %>

  </div>

  <div id="page_id" class="span6">
    <%= render 'paginate_survey' %>
  </div>
  <div id="page_id2" class="span6">
    <% if current_owner.is_chain_owner? %>
      <div id="request_menu" style="display:none;">
        <%= link_to "Reject", "#", :class => 'btn right', :onclick => "prepare_process('reject');" %>
        <%= link_to "Approve", "#", :class => 'btn right', :onclick => "prepare_process('process');" %>
      </div>
        &nbsp;
    <% end %>
    <%= form_tag process_request_owner_surveys_path, :remote => true do %>
        <%= hidden_field_tag "request_ids", nil %>
        <%= hidden_field_tag "mode", nil %>
        <%= submit_tag "submit", :id => 'btn_process', :class => "hide" %>
    <% end %>
  </div>
</div>
<script>
    function prepare_process(mode){
      var mode_str = mode;
      if (mode_str == 'process'){
          mode_str = 'approve';
      }
      $('#alertModal1 .modal-body').html('Do you want to '+mode_str+' all selected requests ?');
      $('#alertModal1-ok').attr("onclick", "process_all('"+mode+"', true);");
      $('#alertModal1-cancel').attr("onclick", "process_all('"+mode+"', false);");
      $('#alertModal1').modal('show');
    }

    function process_all(mode, run) {
        $('#request_ids').val('');
        $("input:checkbox").each(function(){
            var $this = $(this);
            if($this.is(":checked")){
                x = $('#request_ids').val() +'_'+ $this.attr("id").replace('waiting-','');
                $('#request_ids').val(x) ;
            }
        });

        if (run == true) {
            $('#mode').val(mode);
            $('#x-records').ajaxloader();
            $('#btn_process').click();
        }
        else {
            $('#request_ids').val('');
        }

    }

</script>

<div class="table-wrapper products-table section">
  <div class="row-fluid" id="tableContainer">
    <%= render 'all_survey_list' %>
  </div>
</div>

<!-- Modal -->
<div id="surModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <h3 id="myModalLabel">Survey Download</h3>
  </div>

  <div class="modal-body" style="text-align:center;">
    <%= form_tag submit_request_csv_owner_surveys_path, :remote => true do %>
        <%= hidden_field_tag "survey_id_hidden",nil %>
        <%= hidden_field_tag "rotating_id",nil %>
        Start Date <%= text_field_tag "start_date" ,nil, :class => "x-datepicker-day",
                                      :readonly => true,:style=> "cursor:pointer;"%><br/>
        <div id="end_date_show" style="display: none;;">
          End Date <%= text_field_tag "end_date",nil,
                                      :class => "x-datepicker-max-day",
                                      :readonly => true,
                                      :style=> "cursor:pointer;"%><br/>
        </div>
        <i id="notif_survey_popup"></i>
        <%= submit_tag "Submit", :style => "display:none;", :id => "submit_survey_csv" %>
    <% end %>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
    <%= link_to "OK", "#", :class => "btn",:onclick => "$('#submit_survey_csv').click();$('.modal-footer').html('Please Wait ....');return false;" %>
  </div>
</div>
<!-- end modal -->

<% content_for :javascript_script do %>
    <script>
        function confirm_survey(survey_id,rotating) {

            if(rotating){
                $('#rotating_id').val(rotating);
                $('#survey_id_hidden').val('');
                $("#survey_export_" + survey_id + '_rotating').click();
            }else
            {
                $('#rotating_id').val('');
                $('#survey_id_hidden').val(survey_id);
                $("#survey_export_" + survey_id).click();
            }
            return false;
        }


        $(document).ready(function () {
            $('.survey_export').click(function () {
                $('#survey_load').click();
            });
            $('.survey_export_rotate').click(function () {
                $('#survey_load').click();
            });
            $('#graph').click(function () {
                $('#data-container').html('<%= image_tag "spinner.gif", :style => "margin-left: 525px;margin-top: 20px;text-align: center;" %>');
            });
            $('#tb').click(function () {
                $('#data-container').html('<%= image_tag "spinner.gif", :style => "margin-left: 525px;margin-top: 20px;text-align: center;" %>');
            });


            $('.x-datepicker').datepicker({dateFormat:'yy-mm-dd'});
            $('.survey_csv').click(function () {
                var id = this.id.replace('survey_', '');
                $('#download_survey_id').val(id);
            });

            $(".x-datepicker-day").datepicker({
                onSelect:function (theDate) {
                    var d1 = $('#start_date').datepicker("getDate");
                    var d2 = $('#start_date').datepicker("getDate");
                    d1.setDate(d1.getDate() + 30); // change to + 29 if

                    $("#end_date").datepicker("option", "maxDate", d1);
                    $("#end_date").datepicker("option", "minDate", d2);
                    $('#end_date_show').show();
                },
                beforeShow:function () {
                    $('#ui-datepicker-div').css('z-index', 9999);
                },
                dateFormat:'yy-mm-dd'
            });

            $(".x-datepicker-max-day").datepicker({

                beforeShow:function () {
                    $('#ui-datepicker-div').css('z-index', 9999);
                },
                dateFormat:'yy-mm-dd'
            });
        });
    </script>
<% end %>
<% content_for :modal do %>
    <%= render 'owner/guest_relations/help' %>
<% end %>

app/views/owner/surveys/process_request.js.erb
<% @ids.each do |id|  %>
 $('#request_<%= id%>').html('<%= escape_javascript(render :partial => "status", :locals => {:id => id}) %>')
<% end %>

<%
    chain_ids = current_owner.chains.map(&:id)
    request_count = GuestRelation.where("chain_id in(?) and status = 1", chain_ids).count if current_owner.is_chain_owner?
%>

<% if request_count.to_i > 0 %>
	$('#surveys-menu').html('<a href="<%= owner_surveys_path %>" style="padding-bottom: 25px; padding-top: 10px;"><i class="icon-Surveys"></i><span>Surveys</span></a><a href="<%= all_survey_owner_surveys_path %>" style="border: 0px none; position: absolute; box-shadow: none; padding: 0px; margin: 0px; width: auto; top: 30px;"><span class="badge badge-important"><%= request_count %></span></a>');
<% else %>
	$('#surveys-menu').html('<a href="<%= owner_surveys_path %>" ><i class="icon-Surveys"></i><span>Surveys</span></a>');
<% end %>

$('#x-records').ajaxloader('hide');
$('#request_menu').hide();
$('#select_all').attr('checked',false);