config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  require 'sidekiq/web'

  match '/auth/:provider/callback' => 'authentications#create', via: [:get, :post]
  match '/auth/failure' => 'authentications#failure', via: [:get, :post]

  match '/auth/olo/authorize' => 'auth#authorize', via: [:get, :post]
  match '/auth/olo/authorize_mobile_app' => 'auth#authorize_mobile_app', via: [:get, :post]
  match '/auth/olo/access_token' => 'auth#access_token', via: [:get, :post]
  match '/auth/olo/user' => 'auth#user', via: [:get, :post]
  match '/auth/olo/logout' => 'auth#session_destroy', via: [:get, :post]
  match '/oauth/token' => 'auth#access_token', via: [:get, :post]

  match 'authentications/:user_id/link' => 'authentications#link', :as => :link_accounts, via: [:get, :post]
  match 'authentications/:user_id/add' => 'authentications#add', :as => :add_account, via: [:get, :post]

  match "login_oauth" => "authentications#login_oauth", :as => :login_oauth, via: [:get, :post]

  get "users/:id/email_confirm" => "menus#confirm_email", :as => :confirm_email
  get "terms_of_use" => "menus#terms_of_use", :as => :tou
  get "privacy_policy" => "menus#privacy_policy", :as => :privacy_policy
  get "faq" => "menus#faq", :as => :faq
  get "faqs/:faq_data" => "menus#generated_faq", :as => :generated_faq
  get "about_us" => "menus#about_us", :as => :about_us
  get "contact_us_faq" => "menus#contact_us_faq", :as => :contact_us_faq
  get "game_faq" => "menus#game_faq", :as => :game_faq
  get "url/:chain_id/:url_id" => "menus#url", :as => :chain_url
  get "download_reward_transactions" => "menus#download_reward_transactions", :as => :download_reward_transactions
  get 'receipt/:url_id' => "menus#show_receipt", :as => :show_receipt
  post "status_url_skrill_payment" => "menus#status_url_skrill_payment", :as => :status_url_skrill_payment

  post "olo_webhook/:chain_name", :to => "api/v1/olo_webhooks#create_olo"
  get "receive", :to => "api/v1/olo_webhooks#index"

  devise_for :owners, :controllers => { :sessions => "owner/sessions" }
  devise_scope :owner do
   get "owner/log_in", :to => "owner/sessions#new"
   post "owner/log_in", :to => "owner/sessions#create"
   get "owner/log_out", :to => "owner/sessions#destroy"
 end

  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end

  devise_scope :owner do
    get "owner/log_in", :to => "owner/sessions#new"
    post "owner/log_in", :to => "owner/sessions#create"
    get "owner/log_out", :to => "owner/sessions#destroy"
    put "owner/:id" => 'owner/registrations#update', :as => 'owner_registration_update'
  end

  namespace :owner do
    resources :greetings, :path => "/summaries" do
      collection do
        get :search_summaries
        get :export_summaries
      end
    end

    resources :guest_relations, :path => "/request" do
      collection do
        get :search_status_relation
      end

      member do
        get "check_status_relation"
        post "update_status_relation"
        get "approve_or_reject"
      end
    end

    resources :owner_jobs, :path => "/jobs" do
      collection do
        get :search_users
        get :miss_you
        get :new_miss_you
        get :individual
        post :create_individual
        post :create_miss_job
        get :search_job_type
      end
      member do
        get 'completed_job'
      end
    end
    resources :members do
      collection do
        post :send_message
        post :search
      end
    end
    resources :owner_users do
      collection do
        get :export_pdf, :format => :pdf
      end
    end
    resources :surveys do
      collection do
        match '/all_survey' => "surveys#all_survey", via: [:get, :post]
        get :export_survey_dashboard
        get :search_location_survey
        get :search_all_survey
        get :search
        get :search_chart
        post :process_request
        get :request_csv
        post :submit_request_csv
      end

      member do
        get "request_guest_relation"
        post "request_guest"

      end
    end
    resources :rewards
    resources :activities do
      collection do
        get :search_activities
        post :generate_restaurant
        post :generate_restaurant_rewards
        post :print_row_tables
        post :print_row_tables_rewards
        get :rewards
        post :export_rewards_redeemed
        post :export_activities
      end
      member do
        get :show_detail_receipt
        get :show_detail_reward
        get :show_popup_reward_activities
        get :show_receipt_barcode
        get :show_online_order
        get :show_olo_order
      end
    end
  end

  resource :charts do
    collection do
      get :active_members
      get :members
      get :average_frequency
      get :average_check_frequency
      get :frequency
      get :top5_surveys
      get :average_surveys
      get :avg_surveys
      get :survey_question1
      get :survey_question2
      get :survey_question3
      get :survey_question4
    end
  end

  scope '(:locale)' do
    devise_for :admin, skip: :registrations, controllers: {sessions: 'admin/sessions'} do
      get "sign_in" , to: "admin/sessions#new", as: :admin_sign_in
      get "log_in" , to: "admin/sessions#new", as: :new_admin_log_in
      post "log_in" , to: "admin/sessions#create", as: :admin_log_in
      get "log_out" , to: "admin/sessions#destroy", as: :admin_log_out
    end
  end
  devise_for :users, :controllers => {
    :sessions => "user/sessions", :registrations => "user/registrations", :omniauth_callbacks=>'user/omniauth_callbacks',
    :passwords => "user/passwords"
  }
  devise_scope :user do
    get "user/log_in", :to => "user/sessions#new"
    post "user/log_in", :to => "user/sessions#create"
    get "user/log_out", :to => "user/sessions#destroy"
  end

  namespace :admin do
    mount Sidekiq::Web => '/sidekiq_redis'

    resources :partner_rewards do
      collection do
        post :search
        get :search
        get :load_categories
        get :load_restaurants
      end
    end
    resources :partner_categories do
      resources :partner_sub_categories
    end
    resources :partner_sub_categories do
      collection do
        post :load_restaurants
        get :load_menu_items
      end
      member do
        post :update_participation
        post :add_item
        post :remove_item
        get :search_menu_items
      end
    end
    resources :partner_menu_items do
      collection do
        post :load_restaurants
      end
    end
    resources :partner_code_settings do
      collection do
        post 'search', :to => "partner_code_settings#search"
      end
    end
    resources :partner_webhook_settings do
      collection do
        post 'search', :to => "partner_webhook_settings#search"
      end
    end

    resources :vantiv_gift_card_email_sent_logs, except: [:edit, :update, :destroy, :new, :create] do
      collection do
        match "search", via: [:get, :post]
      end

      member do
        post :resend_mail
      end
    end
    resources :push_service_notifications, except: [:edit, :update, :destroy], path: "push_services" do
      member do
        get "progress"
        get "cancel"
        get "resume"
        get "pause"
        get 'load_user_list'
      end
      collection do
        get 'sync'
        get 'get_time'
        get 'dashboard'
        get 'ipost'
      end
    end
    resources :push_service_points, except: [:edit, :update, :destroy] do
      member do
        get "progress"
        get "cancel"
        get "resume"
        get "pause"
      end
      collection do
        get 'sync'
      end
    end

    resources :papa_murphys, as: :papa_murphy_reports
    resources :webhooks do
      member do
        get "process_receipt_olo"
      end
    end

    resources :olo_orders do
      collection do
        post 'search'
        match 'olo_receipt_detail', :as => :olo_receipt_detail, via: :get
      end
      member do
        get "order_details"
        match "/order_details/:detail_id" ,:to => "olo_orders#olo_order_show", :via => :get , :as => :olo_order_show
        match "/order_detail_edit/:detail_id" ,:to => "olo_orders#olo_order_edit", :via => :get , :as => :olo_order_edit
        get "process_olo_detail"
        put "post_detail_olo"
        post "batch_process"
      end
    end

    resources :comments, :path => 'email_list' do
      member do
        get "update_email_process" => "comments#update_email_process"
        get "process_receipt" => "comments#process_receipt"
        get "nokogiri_parse_email" => "comments#nokogiri_parse_email"
      end
    end

    resources :miss_you_tasks do
      collection do
        get 'search'
        get 'testing_activation'
      end
      member do
        get 'sending_report'
        post 'post_sending_report_miss_you'
        get 'completed_job'
        put 'update_from_admin'
        get 'update_step',:format => :js
        post 'update_step_ajax',:format => :js
      end
    end

    resources :no_scan_tasks do
      collection do
        get 'search'
        get 'testing_activation'
      end
      member do
        get 'completed_job'
        put 'update_from_admin'
        get 'update_step',:format => :js
        post 'update_step_ajax',:format => :js
      end
    end

    resources :owner_jobs do
      collection do
        get 'search'
        get 'testing_activation'
      end
      member do
        get 'completed_job'
        put 'update_from_admin'
        get 'update_step',:format => :js
        post 'update_step_ajax',:format => :js
      end
    end
    resources :jobs
    resources :admin_jobs,:except => [:show, :edit, :destroy, :update]

    resources :report_subscriptions do
      collection do
        get "search_chain"
        get "search_report_description"
        get "report_settings"
        post "post_test_report"
      end

      member do
        get "subscription_filename"

app/models/partner_menu_item.rb
class PartnerMenuItem < ActiveRecord::Base

  belongs_to :chain
  has_many :restaurant_category_menu_items
  has_many :partner_menu_items_restaurants
  has_many :restaurants, :through => :partner_menu_items_restaurants

  validates :chain_id, :item_name, presence: true

  def pullout(restaurants)
    self.partner_menu_items_restaurants.where("restaurant_id in (?)", restaurants).delete_all
  end

  def participate(restaurants)
    p "partner Menu Item"
    restaurants.each do |restaurant_id|
      existing_deleted_restaurant_category = PartnerMenuItemsRestaurant.unscoped.where("partner_menu_item_id = ? AND restaurant_id = ? ", self.id, restaurant_id).first
      if existing_deleted_restaurant_category.blank?
        existing_restaurant_category = PartnerMenuItemsRestaurant.where("partner_menu_item_id = ? AND restaurant_id = ?", self.id, restaurant_id).first
        PartnerMenuItemsRestaurant.create(:partner_menu_item_id => self.id, :restaurant_id => restaurant_id) if existing_restaurant_category.blank?
      else
        existing_deleted_restaurant_category.revive
      end
    end
  end

end

app/controllers/admin/partner_menu_items_controller.rb
class Admin::PartnerMenuItemsController < Admin::BaseController

  def index
    if params["search"] && params["search"]["chain_id"].present?
      @chain = Chain.find( params["search"]["chain_id"])
      @restaurants = @chain.restaurants.select("id,name,address").order("name ASC")
      @restaurant_id = params["search"]["restaurant_id"] rescue nil
      if @restaurant_id
        @partner_menu_items = @chain.partner_menu_items.includes("partner_menu_items_restaurants").where("partner_menu_items_restaurants.restaurant_id = #{@restaurant_id}")
        .order("partner_menu_items.updated_at ASC").paginate(:page => params[:page], :per_page => 10)
      else
        @partner_menu_items = @chain.partner_menu_items.order("updated_at ASC").paginate(:page => params[:page], :per_page => 10)
      end
    else
      @partner_menu_items = PartnerMenuItem.order("updated_at ASC").paginate(:page => params[:page], :per_page => 10)
      @chain = nil
    end
  end

  def new
    @partner_menu_item = PartnerMenuItem.new
  end

  def create
    chain = Chain.find(params[:partner_menu_item][:chain_id]) rescue nil
    redirect_to new_admin_partner_menu_item_path, :alert => "Invalid Chain" and return if chain.blank?
    locations = params[:restaurants] rescue nil
    redirect_to new_admin_partner_menu_item_path, :alert => "Locations can't be blank." and return if locations.blank?
    xml_in_nokogiri_format = Nokogiri::XML(params[:menu_data])
    redirect_to new_admin_partner_menu_item_path, :alert => "Bad XML Menu Data" and return if xml_in_nokogiri_format.children.blank?

    Delayed::Job.enqueue(PartnerMenuItemParticipatingJob.new(chain, params[:menu_data], params[:restaurants])) if params[:restaurants].present?
    redirect_to admin_partner_menu_items_path, :notice => "Upload Success"
  end

  def edit
    @partner_menu_item = PartnerMenuItem.find params[:id]
    @chain = @partner_menu_item.chain
    @categories = @chain.partner_sub_categories.select("id,name")
  end

  def destroy
    @partner_menu_item = PartnerMenuItem.find params[:id]
    @partner_menu_item.destroy
    redirect_to admin_partner_menu_items_path, :notice => "Partner Category successfully destroyed."
  end

  def load_restaurants
    chain = Chain.find(params[:chain_id])
    @restaurants = chain.restaurants.select("id,name,address").order("name ASC")
    p "@restaurants #{@restaurants.count}"
    @page = params[:page]
  end

end

app/views/admin/partner_menu_items/_form.html.erb
<%= simple_form_for([:admin, @partner_menu_item], id: "partnerCategory") do |f| %>
  <% if @partner_menu_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@partner_menu_item.errors.count, "error") %> prohibited this chain from being saved:</h2>

      <ul>
        <% @partner_menu_item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br/>
  <div class="x-box">
    <div class="field">
      <label class="integer required control-label" for="partner_menu_item_chain"><abbr title="required">*</abbr> Chain</label>
      <%= f.select :chain_id, options_from_collection_for_select(Chain.order("name"), :id, :name, (@chain.id rescue nil) ), {:prompt => "Select Chain"} %>
      <span id="loader-chain" style="display: none;"><%= image_tag "loader.gif" %></span>
    </div>

    <div class="field">
      <%= label_tag :menu_data %>
      <%= text_area_tag :menu_data, nil, rows: 15, style: "width:400px;" %>
    </div>

    <div id="box-restaurant">
      <%= render partial: "restaurant" if @restaurants %>
    </div>

    <br/><br/>
    <%= f.submit "Upload", :class => "btn btn-primary" %>
    <%= link_to 'Back', admin_partner_menu_items_path, :class => "btn" %>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('select#partner_menu_item_chain_id').change(function(){
      $("#loader-chain").show();
      var chain_id = $("#partner_menu_item_chain_id").val();
      $.post("/admin/partner_menu_items/load_restaurants", { chain_id: chain_id})
    });
  });
</script>

app/views/admin/partner_menu_items/_restaurants.html.erb
<% if @page == "index" %>
  <label class="string required control-label" for="searchrestaurant_id"><abbr title="required">*</abbr> Restaurant</label>
  <%= select_tag "search[restaurant_id]", options_for_select(@restaurants.map { |r| [r.name, r.id]}, selected: @restaurant_id ) %>
<% else %>
  <table>
    <caption>Restaurants:</caption>
    <thead>
    <tr>
      <th width="40px;"></th>
      <th>Name</th>
      <th>Address</th>
      <th></th>
    </tr>
    </thead>
    <tfoot>
    <tr>
      <th colspan="3"></th>
      <th><%= submit_tag "Check All", id: "check-all" %></th>
    </tr>
    </tfoot>
    <tbody>
    <% @restaurants.each_with_index do |restaurant, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= check_box_tag "restaurants_[#{restaurant.id}]", restaurant.id, false, :name => "restaurants[]" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <script type="text/javascript">
    $(document).ready(function(){
      $("#check-all").click(function(){
        if(confirm("Click OK to select all the selected restaurants from this reward")){
          $("table input[type=checkbox]").attr('checked', true);
          return false;
        }else{
          return false;
        }
      });
    });
  </script>
<% end %>

app/views/admin/partner_menu_items/edit.html.erb
<div class="page-header">
  <h1>Edit Partner Menu Item</h1>
</div>

<%= render 'form' %>

app/views/admin/partner_menu_items/index.html.erb
<div class="page-header">
  <h1>Listing Partner Menu Items </h1>
</div>
<%= simple_form_for(:search, :url => admin_partner_menu_items_path, :html => {:method => :get}) do |f| %>
  <div class="x-box">
    <div class="x-box-inner">
      <div class="field">
        <%= f.label :chain_id %>
        <%= f.select :chain_id, options_from_collection_for_select(Chain.order("name"), :id, :name, (params[:search][:chain_id] rescue nil) ) %>
        <span id="loader-chain" style="display: none;"><%= image_tag "loader.gif" %></span>
      </div>
      <div id="box-restaurant">
        <label class="string required control-label" for="search_restaurant_id"><abbr title="required">*</abbr> Restaurant</label>
        <%= select_tag "search[restaurant_id]", options_for_select((@restaurants.map { |r| [r.name, r.id]} rescue []), selected: @restaurant_id ) %>
      </div>
      <%= submit_tag "Search", :class => "btn btn-success" %>
    </div>
  </div>
<% end %>

<div id="content-data">

  <table class="table stripped">
    <thead>
    <tr>
      <th>Chain</th>
      <th>Restaurants</th>
      <th>Item Name</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @partner_menu_items.each do |partner_menu_item| %>
      <tr id="row_<%= partner_menu_item.id %>">
        <td><%= partner_menu_item.chain.try(:name) rescue nil %></td>
        <td><%= partner_menu_item.restaurants.map(&:name).join(",") rescue "-" %></td>
        <td><%= partner_menu_item.item_name %></td>
        <td><%= partner_menu_item.description %></td>
        <td>
          <%#= link_to 'Edit', edit_admin_partner_menu_item_path(partner_menu_item), :class => "btn btn-warning" %>
          <%= link_to 'Destroy', admin_partner_menu_item_path(partner_menu_item), :method => :delete, :class => "btn btn-danger", :confirm => "are you sure?" %>
        </td>
      </tr>
    <% end %>
    </tbody>
    </table>
</div>

<%= will_paginate @partner_menu_items unless @partner_menu_items.blank? %>
<br/>
<%= link_to 'New Partner Menu Item', new_admin_partner_menu_item_path, :class => "btn btn-primary" %>

<script type="text/javascript">
  $(document).ready(function(){
     $('select#search_chain_id').change(function(){
        $("#loader-chain").show();
        var chain_id = $("#search_chain_id").val();
        $.post("/admin/partner_menu_items/load_restaurants", { chain_id: chain_id, page: "index"})
    });
  });
</script>

app/views/admin/partner_menu_items/load_restaurants.js.erb
$("#loader-chain").hide();
$('#box-restaurant').html('<%=j render "restaurants" %>');

app/views/admin/partner_menu_items/new.html.erb
<div class="page-header">
  <h1>New Partner Menu Item</h1>
</div>

<%= render 'form' %>