config/routes.rb
      end
      collection do
        get 'sync'
      end
    end

    resources :papa_murphys, as: :papa_murphy_reports
    resources :webhooks do
      member do
        get "process_receipt_olo"
      end
    end

    resources :olo_orders do
      collection do
        post 'search'
        match 'olo_receipt_detail', :as => :olo_receipt_detail, via: :get
      end
      member do
        get "order_details"
        match "/order_details/:detail_id" ,:to => "olo_orders#olo_order_show", :via => :get , :as => :olo_order_show
        match "/order_detail_edit/:detail_id" ,:to => "olo_orders#olo_order_edit", :via => :get , :as => :olo_order_edit
        get "process_olo_detail"
        put "post_detail_olo"
        post "batch_process"
      end
    end

    resources :comments, :path => 'email_list' do
      member do
        get "update_email_process" => "comments#update_email_process"
        get "process_receipt" => "comments#process_receipt"
        get "nokogiri_parse_email" => "comments#nokogiri_parse_email"
      end
    end

    resources :miss_you_tasks do
      collection do
        get 'search'
        get 'testing_activation'
      end
      member do
        get 'sending_report'
        post 'post_sending_report_miss_you'
        get 'completed_job'
        put 'update_from_admin'
        get 'update_step',:format => :js
        post 'update_step_ajax',:format => :js
      end
    end

    resources :no_scan_tasks do
      collection do
        get 'search'
        get 'testing_activation'
      end
      member do
        get 'completed_job'
        put 'update_from_admin'
        get 'update_step',:format => :js
        post 'update_step_ajax',:format => :js
      end
    end

    resources :owner_jobs do
      collection do
        get 'search'
        get 'testing_activation'
      end
      member do
        get 'completed_job'
        put 'update_from_admin'
        get 'update_step',:format => :js
        post 'update_step_ajax',:format => :js
      end
    end
    resources :jobs
    resources :admin_jobs,:except => [:show, :edit, :destroy, :update]

    resources :report_subscriptions do
      collection do
        get "search_chain"
        get "search_report_description"
        get "report_settings"
        post "post_test_report"
      end

      member do
        get "subscription_filename"
        get "test_report"
        post "post_subscrition_filename"
        put  "post_subscrition_filename"
        get "get_filename_subscription"
      end
    end
    resources :report_definitions do
      member do
        post "activate_deactivate" => "report_definitions#activate_deactivate", :as => :activate_deactivate
        get "edit_parameter"
      end
    end

    resources :reports do
      collection do
        post "search_reports"
      end
    end
    resources :admins
    resources :search, :questions, :choices, :translations, :perks, :promo_codes, :notification_locales

    resources :surveys do
      member do
        get :edit_max_question
        get :set_rotating_position
        post :submit_position_rotating
        put :update_max_question
        post :update_order_number
        get 'set_choice_for_negative_response/:value', :to => "surveys#set_choice_for_negative_response", :as => :set_choice_for_negative_response
        get :pick_incentive
        get :load_onetime_reward
        get :load_points
        get :assign_incentive
        put :add_point
        get 'assign_with_existing_reward/:reward_id', :to => "surveys#assign_with_existing_reward", :as => :assign_with_existing_reward
        get 'edit_point'
        get 'remove_incentive/:type', :to => "surveys#remove_incentive", :as => :remove_incentive
        post :create_reward_incentive
      end

      collection do
        post :group_chain_list
      end
    end

    resources :managers, :except => [:show, :index,:edit, :destroy, :update], :controller => 'owners' do
      collection do
        get '', :to => "owners#managers"
        get 'new', :to => "owners#new_manager"
        get "restaurant_selection_manager", :to => 'owners#restaurant_selection_manager'
        post "create_manager", :to => 'owners#create_manager'
      end
      member do
        get 'list_manager', :to => "owners#show_managers"
        get 'edit', :to => "owners#edit_manager"
        put 'update', :to => "owners#update_manager"
        get "detail",  :to => "owners#detail_manager"
      end
    end

    resources :owners do
      collection do
        get "unknown_owner"
        get "question_to"
        get "restaurant_selection"
        post "set_email_to"
        post "select_chain"
        post "set_email_confirmation"
      end
      member do
        get "detail"
        get "dashboard_setting"
        get "set_user_owner_status"
        get "edit_permission"
        get "set_take_action_setting"
        get "set_take_action_setting_new"
        post "post_setting"
      end
    end

    resources :offers do
      collection do
        post "group_chain_list"
      end
      member do
      end
      resources :offer_rules do
        member do
          get 'general_rule_items'
          get "update_rule_status"
          get 'add_general_rule_item/:menu_item_id' => 'offer_rules#add_general_rule_item', :as => 'add_general_rule_item'
          get 'remove_general_rule_item/:menu_item_id' => 'offer_rules#remove_general_rule_item', :as => 'remove_general_rule_item'
          get 'set_type/:menu_item_id/:type' => 'offer_rules#set_type', :as => 'set_type'
        end
      end
    end

    resources :online_offers do
      collection do
        post "group_chain_list"
      end
      member do

      end
    end

    resources :restaurants do
      collection do
        get "deleted" => 'restaurants#deleted', :as => :deleted
        get "new_owner"
        get "owner_restaurant_list"
        post "create_owner"
        get "by_chain"
        post "group_chain_list"
        get "import_restaurants"
        post "import_preview"
        post "create_import"
        get "upload_restaurants"
        post "do_upload_restaurants"
        get "ftp_form"
        post "import_by_ftp"
        get "get_list_file_ftp"
        get "import_restaurants_histories"
        get "import_restaurants_status"
      end
      member do
        get 'change_status_restaurant'
        put 'save_status_restaurant'
        get 'revive' => 'restaurants#revive', :as => :revive
        get "avg_visit"
        match "/:user_id/user_visits" ,:to => "restaurants#user_visits", :via => :get , :as => :user_visits
      end
    end

    resources :milestones do
      member do
        get 'new' => 'milestones#new', :as => :new
        get "milestones_by_chain" => 'milestones#milestones_by_chain', :as => :milestones_by_chain
        get 'add_reward' => "milestones#add_reward", :as => "add_reward"
        post 'create_milestone_reward' => 'milestones#create_milestone_reward', :as => "create_milestone_reward"
        get 'edit_reward/:reward_id' => "milestones#edit_reward", :as => 'edit_reward'
        put 'update_milestone_reward/:reward_id' => "milestones#update_milestone_reward", :as => 'update_milestone_reward'
      end
    end

    resources :unsent_android_notifications do
      member do
        get 'remove_regid' => 'unsent_android_notifications#remove_regid', :as => :remove_regid
      end
    end

    resources :queue_notif_settings do

    end

    resources :push_service_notification_certificates do
      collection do
        get "search", :to => "push_service_notification_certificates#index", :as => :search
      end
    end

    resources :applications do
      member do
        get 'set_key' => "applications#set_key", :as =>  :set_key
        get 'change_status/:status' => 'applications#change_status', :as => :change_status
        get 'test_send_apn' => 'applications#test_send_apn', :as => :test_send_apn
        post 'send_apn' => 'applications#send_apn', :as => :send_apn
      end
      resources :application_keys do
        member do
          get 'update_status/:status' => 'application_keys#update_status'
          get 'set_newest_version/:newest' => 'application_keys#set_newest_version'
        end
      end

      resources :certificates do
        collection do
          get 'download'
        end
      end
    end

    resources :referral_programs do
      resources :referral_codes do
        resources :referral_users

        collection do
          get "generate_codes", :to => "referral_codes#generate_codes"
          get "search", :to => "referral_codes#search", :as => :search
        end
      end

      collection do
        get "notifications", :to => "referral_programs#notifications"
        post "search", :to => "referral_programs#search", :as => :search
        match '/:chain_id/new_ref', :to => "referral_programs#new_ref", :via => :get , :as => :new_ref, :format => :js
        match '/:id/:chain_id/edit_ref', :to => "referral_programs#edit_ref", :via => :get , :as => :edit_ref, :format => :js
        match '/:id/:chain_id/show_ref', :to => "referral_programs#show_ref", :via => :get , :as => :show_ref, :format => :js
      end

      member do
        get :pick_incentive, :format => :js
        get :assign_incentive , :format => :js
        get :load_onetime_reward, :format => :js
        get :load_points, :format => :js
        get 'assign_with_existing_reward/:reward_id' => 'referral_programs#assign_with_existing_reward', :as => :assign_with_existing_reward
        post 'create_reward_incentive' => 'referral_programs#create_reward_incentive', :as => :create_reward_incentive
        post 'create_offer_incentive' => 'referral_programs#create_offer_incentive', :as => :create_offer_incentive
        get 'remove_incentive/:incentive_id' => 'referral_programs#remove_incentive', :as => :remove_incentive
        put 'update_incentive' => 'referral_programs#update_incentive', :as => :update_incentive

app/models/referral_program.rb
class ReferralProgram < ActiveRecord::Base
  include KeyUtil
  belongs_to :incentive, :polymorphic => true
  belongs_to :incentive_referer, :polymorphic => true
  belongs_to :chain
  has_many :referral_users
  validates :min_approve, :numericality => {:greater_than => -1} , :allow_nil => true, :if => Proc.new { |f| f.approve }
  #validates :min_approve,:presence => true
  #validates :min_approve, numericality: {only_integer: true}
  #has_many :referral_codes, :dependent => :destroy

  scope :active , -> { where("is_active = ? and start_date <= ? and expiry_date >= ?",true,Date.today,Date.today) }
  scope :by_chain, -> (c) { where("chain_id = ?", c.id)}
  before_save :set_min_approve

  TYPES = {
      "REFEREEANDREFERRER" => 1,
      "REFEREEONLY" => 2,
      "REFERRERONLY" => 3
  }

  def set_min_approve
    if self.approve == false
      self.min_approve = 0
    end
  end

  def generate_referral_codes(chain_obj)
    size = Setting.referral_code.code_size || 10
    chars = Setting.referral_code.code_chars 
    ## referall code uniq / user
    ## delete first
    ReferralCode.where("user_id in (?)", chain_obj.users.map(&:id)).delete_all
    users = self.chain.users
    
    users.each do |u|
      begin
        code = generate_random_string(size, chars)
        ReferralCode.create(:user_id => u.id, :code => code.downcase)        
      rescue => e
        p e
      end
    end
  end

  def set_active_program
    ReferralProgram.by_chain(self.chain).update_all("is_active = false")
    self.update_attribute(:is_active, true)
  end

  def is_active?
    self.start_date <= Date.today and self.expiry_date >= Date.today
  end

  def self.reset_referral(chain)
    rf = ReferralProgram.find_by_chain_id(chain.id)
    rf.destroy if rf
    rc = ReferralCode.by_chain(chain)
    rc.each {|x| x.delete}
    return true
  end

  def get_referral_program_type
    ref_prog = self
    type = nil
    if ref_prog.incentive && ref_prog.incentive_referer
      type = ReferralProgram::TYPES["REFEREEANDREFERRER"]
    elsif ref_prog.incentive
      type = ReferralProgram::TYPES["REFEREEONLY"]
    elsif ref_prog.incentive_referer
      type = ReferralProgram::TYPES["REFERRERONLY"]
    end
    return type
  end
  
end

app/views/admin/referral_programs/incentive/create_incentive.js.erb
<% if @type == "reward" %>

  <% unless @reward.errors.blank? %>
    <% error = @reward.errors %>
    <% @reward.attributes.each do |k,v| %>
      $("#reward_<%=  k %>").removeClass("error");
      $("#<%=k%>_error").html("");
    <% end %>
    $('.tata-ajax-loader').hide();
    <% error.each do |key,value| %>
      $("#reward_<%=key%>").addClass("error");
      $("#<%=key%>_error").html("<span style='color:red;'><%= value %></span>");
    <% end %>
  <% else %>
    <% referer_id = @referer.blank? ? nil : 'referer-' %>
    <% referer_part = @referer.blank? ? nil : 'referer_' %>
    <% referer_att  = @referer.blank? ? nil : true %>
    $("#incentive-<%= referer_id %><%= @referral_program.id %>").html("<%= escape_javascript(render :partial => "admin/referral_programs/partials/incentive_#{referer_part}column", :locals => {:ref => @referral_program, :referer => referer_att}) %>");
    $("#ref_modal").html('<%= escape_javascript(render :partial => "admin/referral_programs/partials/confirmation", :locals => {:message => "Incentive Reward are created"}) %>');
  <% end %>


<% elsif @type == "offer" %>
  <% if @is_save %>
<% referer_id = @referer.blank? ? nil : 'referer-' %>
<% referer_part = @referer.blank? ? nil : 'referer_' %>
<% referer_att  = @referer.blank? ? nil : true %>
    $("#incentive-<%= referer_id %><%= @referral_program.id %>").html("<%= escape_javascript(render :partial => "admin/referral_programs/partials/incentive_#{referer_part}column", :locals => {:ref => @referral_program, :referer => referer_att}) %>");
    $("#ref_modal").html('<%= escape_javascript(render :partial => "admin/referral_programs/partials/confirmation", :locals => {:message => "Incentive Offer are created"}) %>');
  <% else %>
    $("#ref_modal").html('<%= escape_javascript(render "admin/referral_programs/partials/incentive_offer") %>')
  <% end %>
<% else %>

  <% if @is_save %>
<% referer_id = @referer.blank? ? nil : 'referer-' %>
<% referer_part = @referer.blank? ? nil : 'referer_' %>
<% referer_att  = @referer.blank? ? nil : true %>
    $("#incentive-<%= referer_id %><%= @referral_program.id %>").html("<%= escape_javascript(render :partial => "admin/referral_programs/partials/incentive_#{referer_part}column", :locals => {:ref => @referral_program, :referer => referer_att}) %>");
    $("#ref_modal").html('<%= escape_javascript(render :partial => "confirmation", :locals => {:message => "Incentive Offline are created"}) %>');
  <% else %>
    $("#ref_modal").html('<%= escape_javascript(render "admin/referral_programs/partials/incentive_offer") %>')
  <% end %>

<% end %>

app/views/admin/referral_programs/incentive/edit_incentive.js.erb
$('#ref_modal').html("<%= escape_javascript(render "admin/referral_programs/partials/incentive_offer") %>");

app/views/admin/referral_programs/incentive/load_one_time_reward.js.erb
$("#ontime-list").html('<%= escape_javascript(render "admin/referral_programs/partials/rewards") %>');

app/views/admin/referral_programs/incentive/load_points.js.erb
$("#points-list").html('<%= escape_javascript(render "admin/referral_programs/partials/points") %>');

app/views/admin/referral_programs/incentive/remove_incentive.js.erb
<% if @referer.blank? %>
$('#incentive-<%= @referral_program.id %>').html('<%= escape_javascript(link_to "Add Incentive referee","#ref_modal", :onclick => "$('#ref_modal').html('');$.get('#{pick_incentive_admin_referral_program_path(@referral_program)}')","data-toggle" => "modal", :class => "btn") %>')
<% else %>
$('#incentive-referer-<%= @referral_program.id %>').html('<%= escape_javascript(link_to "Add Incentive Referer","#ref_modal", :onclick => "$('#ref_modal').html('');$.get('#{pick_incentive_admin_referral_program_path(@referral_program, :referer => true)}')",
"data-toggle" => "modal", :class => "btn") %>')
<% end %>